services:

# Listeners
    rubencm.storage_flysystem.listener:
        class: rubencm\storage_flysystem\event\listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }

    rubencm.storage_flysystem.attachment_listener:
        class: rubencm\storage_flysystem\event\attachment_listener
        arguments:
            - '@config'
            - '@language'
            - '@storage.attachment'
        tags:
            - { name: event.listener }

    rubencm.storage_flysystem.avatar_listener:
        class: rubencm\storage_flysystem\event\avatar_listener
        arguments:
            - '@config'
            - '@storage.avatar'
        tags:
            - { name: event.listener }

# Adapters
    storage.adapter.aws_s3:
        class: rubencm\storage_flysystem\adapter\aws_s3
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.azure_blob:
        class: rubencm\storage_flysystem\adapter\azure_blob
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.do_spaces:
        class: rubencm\storage_flysystem\adapter\do_spaces
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.dropbox:
        class: rubencm\storage_flysystem\adapter\dropbox
        shared: false
        arguments:
            - '@cache.driver'
        tags:
            - { name: storage.adapter }

    storage.adapter.ftp:
        class: rubencm\storage_flysystem\adapter\ftp
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.google_drive:
        class: rubencm\storage_flysystem\adapter\google_drive
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.openstack_swift:
        class: rubencm\storage_flysystem\adapter\openstack_swift
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.rackspace:
        class: rubencm\storage_flysystem\adapter\rackspace
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

    storage.adapter.sftp:
        class: rubencm\storage_flysystem\adapter\sftp
        shared: false
        arguments:
        tags:
            - { name: storage.adapter }

# Providers
    storage.provider.aws_s3:
        class: rubencm\storage_flysystem\provider\aws_s3
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.azure_blob:
        class: rubencm\storage_flysystem\provider\azure_blob
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.do_spaces:
        class: rubencm\storage_flysystem\provider\do_spaces
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.dropbox:
        class: rubencm\storage_flysystem\provider\dropbox
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.ftp:
        class: rubencm\storage_flysystem\provider\ftp
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.google_drive:
        class: rubencm\storage_flysystem\provider\google_drive
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.openstack_swift:
        class: rubencm\storage_flysystem\provider\openstack_swift
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.rackspace:
        class: rubencm\storage_flysystem\provider\rackspace
        arguments:
        tags:
            - { name: storage.provider }

    storage.provider.sftp:
        class: rubencm\storage_flysystem\provider\sftp
        arguments:
        tags:
            - { name: storage.provider }
